/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;


import CapaLogica.ManejoDeFecha;
import CapaLogica.ManejoDelUsuario;
import CapaDatos.ConexionDB;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import static CapaPresentacion.NutriAppMain.*;

/**
 *
 * @author iJona
 */

public class InterfazLogin extends javax.swing.JFrame {

    public  PanelRegistroUsuario panelRegistroUsuario;
    public static String rutaImagPerfil;
    ConexionDB conexion;
    
    public InterfazLogin() {
       
        initComponents();
        this.setLocationRelativeTo(null);//centrrar pantalla
        fechaActual = ManejoDeFecha.calcularFechaActual();
        diaActual = ManejoDeFecha.calcularDiaActual();
        System.out.println("hoy es "+fechaActual+", "+diaActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonEntrar = new javax.swing.JButton();
        entryId = new javax.swing.JTextField();
        entryPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonRegistrarse = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 406));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoInicioSesion.png"))); // NOI18N
        Panel2.add(jLabel4);

        getContentPane().add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 570, 280));

        Panel1.setBackground(new java.awt.Color(204, 204, 255));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Iniciar Sesión");
        Panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 14, -1, 40));

        botonEntrar.setBackground(new java.awt.Color(102, 102, 102));
        botonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entrar.png"))); // NOI18N
        botonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });
        Panel1.add(botonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 40, 30));
        Panel1.add(entryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 170, -1));
        Panel1.add(entryPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 150, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Cuenta de Usuario");
        Panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Contraseña");
        Panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLogin.png"))); // NOI18N
        Panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 70));

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 70));

        botonRegistrarse.setBackground(new java.awt.Color(0, 51, 51));
        botonRegistrarse.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        botonRegistrarse.setText("Registrarse");
        botonRegistrarse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 90, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backround.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
       
        String cuenta = entryId.getText();
        String pass = entryPass.getText();
        conexion = new ConexionDB(rutaDBUsuarios);
        
        if(ManejoDelUsuario.validarDatosLogin(cuenta, pass)){
            
            usuario = conexion.buscarUsuario(cuenta,pass);
            if (usuario!= null){
                        // conecto al DB diario del usuario
                ConexionDB conx= new ConexionDB("jdbc:ucanaccess://"+usuario.getUrl());
                usuario.setDiarios(conx.recuperarDiarios());
                InterfazPrincipal1.main(null);
                interfazLogin.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "Cuenta de Usuario o contraseña incorrectos");
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Faltan Campos Por Llenar.");
        
        }
    }//GEN-LAST:event_botonEntrarActionPerformed

    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        
        this.panelRegistroUsuario = new PanelRegistroUsuario();
         
        Panel2.removeAll();
        Panel2.add(panelRegistroUsuario, BorderLayout.PAGE_START);
        Panel2.revalidate();
        Panel2.repaint();
        
        botonEntrar.setEnabled(false);
        entryPass.setEnabled(false);
        entryId.setEnabled(false);
        botonRegistrarse.setEnabled(false);
    }//GEN-LAST:event_botonRegistrarseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel1;
    public javax.swing.JPanel Panel2;
    public javax.swing.JButton botonEntrar;
    private javax.swing.JButton botonRegistrarse;
    public javax.swing.JTextField entryId;
    public javax.swing.JPasswordField entryPass;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                
                interfazLogin = new InterfazLogin(); 
                interfazLogin.setVisible(true);
                
            }
        });
    }
}
