/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaLogica.ManejoDeImagenes;
import static CapaPresentacion.InterfazLogin.rutaImagPerfil;
import static CapaPresentacion.InterfazPrincipal2.panelHistorial;
import static CapaPresentacion.InterfazPrincipal2.panelRegistroAlimento;
import static CapaPresentacion.NutriAppMain.usuario;
import java.awt.BorderLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.*;
import static CapaPresentacion.NutriAppMain.interfazPrincipal1;
import static CapaPresentacion.NutriAppMain.interfazPrincipal2;

/**
 *
 * @author iJona
 */
public class InterfazPrincipal1 extends javax.swing.JFrame {


    /**
     * Creates new form InterfazInicial
     */
    public InterfazPrincipal1() {
        initComponents();
        this.setLocationRelativeTo(null);//centro la pantalla
        //  quito los bordes de los botones
        botonConsulta.setContentAreaFilled(false);  
        botonDiario.setContentAreaFilled(false);
        botonHistorial.setContentAreaFilled(false);
        botonInicio.setContentAreaFilled(false);
        botonSalir.setContentAreaFilled(false);
        
        // si entro por primera vez
        if (usuario.Diarios.empty()){       
            // cargo la imagen de la ruta original
            ImageIcon fotoPerfil = new ImageIcon(rutaImagPerfil);
            Icon icono = new ImageIcon(fotoPerfil.getImage().getScaledInstance(labelUser.getWidth(), labelUser.getHeight(), Image.SCALE_DEFAULT));
            labelUser.setIcon(icono);
        }
        else{
            //  cargo la imagen 
            String rutaImag= "/Imagenes/"+usuario.getId()+".jpg";
            URL urlImag = getClass().getResource(rutaImag);
            ImageIcon fotoPerfil = new ImageIcon(urlImag);
            labelUser.setIcon(ManejoDeImagenes.adaptarImagen(fotoPerfil, 60, 60)  );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUser = new javax.swing.JLabel();
        botonInicio = new javax.swing.JButton();
        botonConsulta = new javax.swing.JButton();
        botonDiario = new javax.swing.JButton();
        botonHistorial = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        PanelPrincipal = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 60, 60));

        botonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png"))); // NOI18N
        botonInicio.setText("Inicio");
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 120, 50));

        botonConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonConsulta.png"))); // NOI18N
        botonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(botonConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 160, 50));

        botonDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonDiario.png"))); // NOI18N
        botonDiario.setText("Recordatorio 24h");
        botonDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDiarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 120, 50));

        botonHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonHistorial.png"))); // NOI18N
        botonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(botonHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 140, 50));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 10, 300));

        PanelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelPrincipal.setAlignmentX(0.0F);
        PanelPrincipal.setAlignmentY(0.0F);
        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 490, 330));

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonSalir.png"))); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 82, 60, 20));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fonndoInterfaz1.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cargarPanel(JPanel p){
        
        this.PanelPrincipal.removeAll();
        this.PanelPrincipal.add(p, BorderLayout.CENTER);
        this.PanelPrincipal.revalidate();
        this.PanelPrincipal.repaint();
    }
    
    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        cargarInicio();
     //   botonConsultar.setEnabled(false);
    }//GEN-LAST:event_botonInicioActionPerformed
    
    private void botonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaActionPerformed
        cargarConsulta();
        
    }//GEN-LAST:event_botonConsultaActionPerformed

    private void botonDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDiarioActionPerformed
          
        panelRegistroAlimento = new PanelRegistoAlimento();
        interfazPrincipal2 = new InterfazPrincipal2(0);
        interfazPrincipal2.setVisible(true);
        interfazPrincipal1.setVisible(false);
    }//GEN-LAST:event_botonDiarioActionPerformed

    private void botonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHistorialActionPerformed
        if (!usuario.Diarios.isEmpty()){ //  si la pila de diarios esta vacia...
            panelHistorial =new PanelHistorial();
            interfazPrincipal2 = new InterfazPrincipal2(1);
            interfazPrincipal2.setVisible(true);
            interfazPrincipal1.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "No tienes ningún diario creado hasta el momento");
        }
        
    }//GEN-LAST:event_botonHistorialActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        InterfazLogin.main(null);
        interfazPrincipal1.setVisible(false);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                interfazPrincipal1 = new InterfazPrincipal1();
                interfazPrincipal1.setVisible(true);
                interfazPrincipal1.cargarInicio();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton botonConsulta;
    private javax.swing.JButton botonDiario;
    private javax.swing.JButton botonHistorial;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonSalir;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelUser;
    // End of variables declaration//GEN-END:variables

    public void cargarHistorial() {
         PanelHistorial p = new PanelHistorial();
        this.cargarPanel(p);
    }

    public void cargarConsulta() {
        PanelConsulta p = new PanelConsulta();
        this.cargarPanel(p);
    }

    public void cargarInicio() {
        PanelInicio p = new PanelInicio();
        this.cargarPanel(p);
    }

}
