/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaDatos.ConexionDB;
import CapaLogica.ManejoDeImagenes;
import static CapaPresentacion.NutriAppMain.usuario;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.net.URL;
import javax.swing.ImageIcon;
import static CapaPresentacion.NutriAppMain.interfazPrincipal1;
import static CapaPresentacion.NutriAppMain.interfazPrincipal2;


/**
 *
 * @author iJona
 */
public class InterfazPrincipal2 extends javax.swing.JFrame {

    /**
     * Creates new form InterfazIniciall
     */
    ConexionDB conexion=null ;
    public static PanelRegistoAlimento panelRegistroAlimento;
    public static PanelDiarios panelTiemposComida;
    public static PanelHistorial panelHistorial;
    
   public InterfazPrincipal2(int n_panel) {
        
        initComponents();
        
        //  cargo fotoPerfil
        String rutaImagPerfil = "/Imagenes/"+usuario.getId()+".jpg";
        URL urlImag = getClass().getResource(rutaImagPerfil);
        ImageIcon fotoPerfil = new ImageIcon(urlImag);  
        labelUser.setIcon(ManejoDeImagenes.adaptarImagen(fotoPerfil, 60, 60) );
        //  cargo paneles
        panelTiemposComida = new PanelDiarios();
        cargarPanel1();
        cargarPanel2(n_panel);
        this.setLocationRelativeTo(null);//centrrar pantalla
        panelTiemposComida.actualizarTablaDiarios(usuario.Diarios.peek());
        //  quito los bordes de los botones
        botonCerrarSesion.setContentAreaFilled(false);
        botonConsulta.setContentAreaFilled(false);
        botonDiario.setContentAreaFilled(false);
        botonHistorial.setContentAreaFilled(false);
        botonInicio.setContentAreaFilled(false);
        botonCerrarSesion.setContentAreaFilled(false);
    }

    public void cargarPanel1(){
        
        Panel1.removeAll();
        Panel1.add(panelTiemposComida, BorderLayout.CENTER);
        Panel1.revalidate();
        Panel1.repaint();
    }
    public void cargarPanel2( int n){
        
        Panel2.removeAll();
        if ( n == 0)        Panel2.add(panelRegistroAlimento, BorderLayout.CENTER);
        else if ( n == 1)        Panel2.add(panelHistorial, BorderLayout.CENTER);
        
        Panel2.revalidate();
        Panel2.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        labelUser = new javax.swing.JLabel();
        botonInicio = new javax.swing.JButton();
        botonDiario = new javax.swing.JButton();
        botonHistorial = new javax.swing.JButton();
        botonConsulta = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        botonCerrarSesion = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(920, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 10, 540));
        getContentPane().add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 60, 60));

        botonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png"))); // NOI18N
        botonInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonInicio.setBorderPainted(false);
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 150, 50));

        botonDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonDiario.png"))); // NOI18N
        botonDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDiarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 150, 50));

        botonHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonHistorial.png"))); // NOI18N
        botonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(botonHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 160, 60));

        botonConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonConsulta.png"))); // NOI18N
        botonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(botonConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 160, 50));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 10, 360));

        botonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonSalir.png"))); // NOI18N
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 80, -1));
        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 368, 558));
        getContentPane().add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 290, 370));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fonndoInterfaz2.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
       
        interfazPrincipal1 = new InterfazPrincipal1();
        interfazPrincipal1.cargarInicio();
        interfazPrincipal1.setVisible(true); 
        interfazPrincipal2.setVisible(false);
    }//GEN-LAST:event_botonInicioActionPerformed

    private void botonDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDiarioActionPerformed
        
        panelTiemposComida = new PanelDiarios();
        cargarPanel1();
        panelRegistroAlimento = new PanelRegistoAlimento() ;
        cargarPanel2(0);
        panelTiemposComida.actualizarTablaDiarios(usuario.Diarios.peek());
    }//GEN-LAST:event_botonDiarioActionPerformed

    private void botonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHistorialActionPerformed
        panelTiemposComida = new PanelDiarios();
        this.cargarPanel1();
        panelHistorial = new PanelHistorial() ;
        this.cargarPanel2(1);
        panelTiemposComida.actualizarTablaDiarios(usuario.Diarios.peek());
        
        
    }//GEN-LAST:event_botonHistorialActionPerformed

    private void botonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaActionPerformed
        
        interfazPrincipal1 = new InterfazPrincipal1();
        interfazPrincipal1.cargarConsulta();
        interfazPrincipal1.setVisible(true);
        interfazPrincipal2.setVisible(false);
        
    }//GEN-LAST:event_botonConsultaActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        // TODO add your handling code here:
        InterfazLogin.main(null);
        interfazPrincipal2.setVisible(false);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonConsulta;
    private javax.swing.JButton botonDiario;
    private javax.swing.JButton botonHistorial;
    private javax.swing.JButton botonInicio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelUser;
    // End of variables declaration//GEN-END:variables

}
