/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Clases.DiarioDietetico;
import Clases.Registro;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author iJona
 */
public class PanelDiarios extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrosDelDiario
     */
    public PanelDiarios() {
        initComponents();
        TableColumnModel moldeTabDesayuno = tablaDesayuno.getColumnModel();
        TableColumnModel moldeTabAlmuerzo = tablaAlmuerzo.getColumnModel();
        TableColumnModel moldeTabCena = tablaCena.getColumnModel();
        TableColumnModel moldeTabRefrigerio = tablaRefrigerio.getColumnModel();
        
        redimencionar(moldeTabDesayuno);
        redimencionar(moldeTabAlmuerzo);
        redimencionar(moldeTabCena);
        redimencionar(moldeTabRefrigerio);
        
    }
    public void redimencionar(TableColumnModel  molde){
        molde.getColumn(0).setPreferredWidth(95);
        molde.getColumn(1).setPreferredWidth(163);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDesayuno = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaAlmuerzo = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaCena = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaRefrigerio = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDesayuno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Alimento", "Calorias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaDesayuno);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, 100));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Desayuno");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Almuerzo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        tablaAlmuerzo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Alimento", "Calorias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaAlmuerzo);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 350, 100));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Cena");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        tablaCena.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Alimento", "Calorias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaCena);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 350, 100));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("Refrigerio");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        tablaRefrigerio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Alimento", "Calorias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaRefrigerio.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane9.setViewportView(tablaRefrigerio);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 350, 100));

        jSeparator4.setToolTipText("");
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 280, 10));

        jSeparator6.setToolTipText("");
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 280, 10));

        jSeparator7.setToolTipText("");
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 300, 10));

        jSeparator8.setToolTipText("");
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 270, 10));

        jLabel1.setBackground(new java.awt.Color(204, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondosTablas.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 560));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable tablaAlmuerzo;
    private javax.swing.JTable tablaCena;
    private javax.swing.JTable tablaDesayuno;
    private javax.swing.JTable tablaRefrigerio;
    // End of variables declaration//GEN-END:variables

     public void actualizarTablaDiarios(DiarioDietetico auxDiario) {
        
       
        DefaultTableModel moldeTabDesayuno = (DefaultTableModel)tablaDesayuno.getModel();
        DefaultTableModel moldeTabAlmuerzo = (DefaultTableModel)tablaAlmuerzo.getModel();
        DefaultTableModel moldeTabCena = (DefaultTableModel)tablaCena.getModel();
        DefaultTableModel moldeTabRefrigerio = (DefaultTableModel)tablaRefrigerio.getModel();
        
        agregarATab(moldeTabDesayuno, auxDiario.desayuno.getRegistros());
        agregarATab(moldeTabAlmuerzo,   auxDiario.almuerzo.getRegistros());
        agregarATab(moldeTabCena, auxDiario.cena.getRegistros());
        agregarATab(moldeTabRefrigerio,  auxDiario.refrigerio.getRegistros());
    }
     
    public void agregarATab(DefaultTableModel molde, ArrayList<Registro> aux) {
        
        for ( int i = 0; i < aux.size(); i++){
            Object registro []= new Object[]{aux.get(i).getPorcion(),   aux.get(i).getAlimento(),   aux.get(i).getCalorias()};
            molde.addRow(registro);  
        }
       
    }

}
