
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CapaPresentacion;

import static CapaPresentacion.InterfazPrincipal2.panelTiemposComida;
import static CapaPresentacion.NutriAppMain.usuario;
import java.awt.BorderLayout;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Clases.DiarioDietetico;
import static CapaPresentacion.NutriAppMain.interfazPrincipal2;

/**
 *
 * @author iJona
 */

public class PanelHistorial extends javax.swing.JPanel {

    
    /**
     * Creates new form JPanel
     */
    PanelTablaHistorial panelTab = null;

    public PanelHistorial() {
        initComponents();
        
        labelReqCal.setText(String.valueOf(usuario.getRequerimientoEnergetico()));
        panelTab = new PanelTablaHistorial();
        cargarTabla();
        ///////////////////
        
        Stack <DiarioDietetico> auxDiarios = (Stack <DiarioDietetico>) usuario.Diarios.clone();
        int i = 0;
        int tam = auxDiarios.size();
        while (i < 7 && i<tam){     //  para agregar los 7 ultimos diarios
            DiarioDietetico aux = auxDiarios.pop();
            if (i==0){
                selecDia.setSelectedIndex(aux.getDd()-1);
                selecMes.setSelectedIndex(aux.getMm()-1);
                selecAño.setSelectedIndex(0);      
            }
            DefaultTableModel molde = (DefaultTableModel)panelTab.tablaHistorial.getModel();
            Object registro []= new Object[]{aux.getDd(),   aux.getDia(),   aux.getNumeroCalorias()};
            molde.addRow(registro);        
            i++;
        }
        System.out.println("num diarios: "+usuario.Diarios.size());
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelReqCal = new javax.swing.JLabel();
        selecAño = new javax.swing.JComboBox<>();
        selecDia = new javax.swing.JComboBox<>();
        selecMes = new javax.swing.JComboBox<>();
        PanelTabH = new javax.swing.JPanel();
        labelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Año");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Mes");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        botonBuscar.setText("buscar");
        botonBuscar.setBorder(new javax.swing.border.MatteBorder(null));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 60, 30));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Dia");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Requerimiento Energético: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        labelReqCal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelReqCal.setForeground(new java.awt.Color(102, 0, 102));
        labelReqCal.setText("1200");
        add(labelReqCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 30));

        selecAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016" }));
        selecAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecAñoActionPerformed(evt);
            }
        });
        add(selecAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        selecDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        selecDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecDiaActionPerformed(evt);
            }
        });
        add(selecDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        selecMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        add(selecMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        add(PanelTabH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 140));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoHistorial.png"))); // NOI18N
        add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        
        String dia = (String) selecDia.getSelectedItem();
        String mes = String.valueOf(selecMes.getSelectedIndex() +1);
        String anio = (String)selecAño.getSelectedItem();
        
        String fecha = dia+"/"+mes+"/"+anio;
        System.out.println("fecha buscar: "+fecha);
        DiarioDietetico diario= null;
        Stack<DiarioDietetico> diarios = (Stack <DiarioDietetico>) usuario.Diarios.clone();
        
         int i = 0;
         boolean encontro = false;
         int tam = diarios.size();
        while (!encontro && i<tam ){
            diario = diarios.pop();
            if (fecha.equals(diario.getFecha())){
                panelTiemposComida = new PanelDiarios();
                interfazPrincipal2.cargarPanel1();
                actualizarTablaHistorial(diarios, diario);
                panelTiemposComida.actualizarTablaDiarios(diario);
                encontro = true;
            }
            i++;
        }
        if (!encontro)        JOptionPane.showMessageDialog(this, "No dispones de un diario con esa fecha\nRecuerda que tu primer diario fue "
                    + "el "+usuario.Diarios.get(0).getFecha());       
        
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void selecDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecDiaActionPerformed

    private void selecAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecAñoActionPerformed
    public void actualizarTablaHistorial(Stack<DiarioDietetico> diarios,DiarioDietetico primerDiario) {
        
        panelTab = new PanelTablaHistorial();
        cargarTabla();
        DefaultTableModel molde = (DefaultTableModel)panelTab.tablaHistorial.getModel();
        Object PrimerRegistro []= new Object[]{primerDiario.getDd(),   primerDiario.getDia(),   primerDiario.getNumeroCalorias()};
        molde.addRow(PrimerRegistro); 
        int i=0;   
        int tamDiarios =diarios.size();
        while (i < tamDiarios && i < 6){
            DiarioDietetico diario = diarios.pop();
            Object registro []= new Object[]{diario.getDd(),   diario.getDia(),   diario.getNumeroCalorias()};
            molde.addRow(registro); 
            i++;
        }
    }

    public void cargarTabla() {
        
        PanelTabH.removeAll();
        PanelTabH.add(panelTab, BorderLayout.CENTER);
        PanelTabH.revalidate();
        PanelTabH.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelTabH;
    public javax.swing.JButton botonBuscar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelFondo;
    public javax.swing.JLabel labelReqCal;
    public javax.swing.JComboBox<String> selecAño;
    public javax.swing.JComboBox<String> selecDia;
    public javax.swing.JComboBox<String> selecMes;
    // End of variables declaration//GEN-END:variables

    
    
        
}
