/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import static CapaPresentacion.NutriAppMain.usuario;
import java.net.URL;
import java.util.TimerTask;
import javax.swing.*;
import java.util.Timer;


/**
 *
 * @author iJona
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    static int cont = 0;
    public void cambiarTips(){
        
        Timer timer;
        TimerTask tarea;
        tarea = new TimerTask() {
            @Override
            public void run() {
                Icon icono;
         
                if (cont == 0){
                    cont = 1;
                    icono = new ImageIcon(getClass().getResource("/imagenes/tip1.png"));
                    labelTips.setIcon(icono);
                }
                else if (cont == 1){
                    cont = 2;
                    icono = new ImageIcon(getClass().getResource("/Imagenes/tip2.png"));
                    labelTips.setIcon(icono);
                }
                 else if (cont == 2){
                    cont = 3;
                    icono = new ImageIcon(getClass().getResource("/Imagenes/tip3.png"));
                    labelTips.setIcon(icono);
                }
                 else if (cont == 3){
                    cont = 4;
                    icono = new ImageIcon(getClass().getResource("/Imagenes/tip4.png"));
                    labelTips.setIcon(icono);
                }
                 else if (cont == 4){
                    cont = 5;
                    icono = new ImageIcon(getClass().getResource("/Imagenes/tip5.png"));
                    labelTips.setIcon(icono);
                }
                 else if (cont == 5){
                    cont = 6;
                    icono = new ImageIcon(getClass().getResource("/Imagenes/tip6.png"));
                    labelTips.setIcon(icono);
                }
                 else if (cont == 6){
                    cont = 7;
                    icono = new ImageIcon(getClass().getResource("/Imagenes/tip7.png"));
                    labelTips.setIcon(icono);
                }
                 else if (cont == 7){
                    cont = 0;
                    icono = new ImageIcon(getClass().getResource("/Imagenes/tip8.png"));
                    labelTips.setIcon(icono);
                }
                
            }
        };
        timer = new Timer();
        timer.scheduleAtFixedRate(tarea, 8000, 8000);
        
        
    }
    public PanelInicio() {
        initComponents();
        cambiarTips();
        
        labelNombre.setText(usuario.getNombre());
        labelEdad.setText(usuario.getEdad()+" años");
        labelSexo.setText(usuario.getSexo().name());
        labelRequerimiento.setText(usuario.getRequerimientoEnergetico()+ " calorías");
        labelEstado.setText(usuario.getEstadoNutricionalActual().name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        labelTips = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botonEditar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelRequerimiento = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        labelNom = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(204, 204, 255));
        labelNombre.setText("Jonnathan Peñaranda");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        labelSexo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelSexo.setForeground(new java.awt.Color(204, 204, 255));
        labelSexo.setText("Masculino");
        add(labelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        labelTips.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tip2.png"))); // NOI18N
        add(labelTips, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 180, 330));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Edad ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        labelEdad.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelEdad.setForeground(new java.awt.Color(204, 204, 255));
        labelEdad.setText("21 años ");
        add(labelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setText("Sexo");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        botonEditar.setFont(new java.awt.Font("sansserif", 2, 11)); // NOI18N
        botonEditar.setText("editar");
        botonEditar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });
        add(botonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 50, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, 20));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, 10));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setText("Requerimiento Energético:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        labelEstado.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelEstado.setForeground(new java.awt.Color(204, 204, 255));
        labelEstado.setText("Obesidad Grado 1");
        add(labelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        labelRequerimiento.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelRequerimiento.setForeground(new java.awt.Color(204, 204, 255));
        labelRequerimiento.setText("2015 calorias");
        add(labelRequerimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setText("Estado Nutricional Actual: ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 270, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 270, 10));

        labelNom.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelNom.setText("Nombre ");
        add(labelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoInicio.png"))); // NOI18N
        labelFondo.setToolTipText("");
        add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
        InterfazEditarInfo v_EditarInfo = new InterfazEditarInfo();
        v_EditarInfo.setVisible(true);
    }//GEN-LAST:event_botonEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRequerimiento;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTips;
    // End of variables declaration//GEN-END:variables

}
