/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;


import Enumeraciones.Sexo;
import Enumeraciones.TipoActividadFisica;
import Clases.Usuario;
import CapaDatos.ConexionDB;
import CapaLogica.ManejoDeImagenes;
import CapaLogica.ManejoDelUsuario;
import static CapaPresentacion.InterfazLogin.rutaImagPerfil;
import static CapaPresentacion.NutriAppMain.interfazLogin;
import static CapaPresentacion.NutriAppMain.rutaDBUsuarios;
import static CapaPresentacion.NutriAppMain.usuario;
import javax.swing.*;
import java.net.URL;

/**
 *
 * @author iJona
 */
public class PanelRegistroUsuario extends javax.swing.JPanel {

    ConexionDB conexion ;
    
    public PanelRegistroUsuario() {
        conexion = new ConexionDB(rutaDBUsuarios);
        initComponents();
        String dir = "/imagenes/perfilDefecto.jpg";
        URL urlImag = getClass().getResource(dir);
        ImageIcon fotoPerfil = new ImageIcon(urlImag);
        labelFoto.setIcon(ManejoDeImagenes.adaptarImagen(fotoPerfil, 94, 88) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecDia = new javax.swing.JComboBox<>();
        selecTipoActFis = new javax.swing.JComboBox<>();
        selecMes = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        selecAnio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        selecSexo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        entryPeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entryTalla = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        entryNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        entryId = new javax.swing.JTextField();
        entryTiempoActFis = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        labelFoto = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        entryPass = new javax.swing.JPasswordField();
        botonImportarImag = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(570, 280));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selecDia.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        selecDia.setForeground(new java.awt.Color(255, 255, 255));
        selecDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        selecDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecDiaActionPerformed(evt);
            }
        });
        add(selecDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 166, -1, -1));

        selecTipoActFis.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        selecTipoActFis.setForeground(new java.awt.Color(255, 255, 255));
        selecTipoActFis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ligera", "Moderada", "Intensa", " " }));
        add(selecTipoActFis, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 215, -1, -1));

        selecMes.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        selecMes.setForeground(new java.awt.Color(255, 255, 255));
        selecMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Novienmbre", "Diciembre" }));
        selecMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecMesActionPerformed(evt);
            }
        });
        add(selecMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 166, -1, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tiempo de Actividad Física");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 248, -1, -1));

        selecAnio.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        selecAnio.setForeground(new java.awt.Color(255, 255, 255));
        selecAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        add(selecAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 166, -1, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 32, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("hrs.");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 248, -1, -1));

        selecSexo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        selecSexo.setForeground(new java.awt.Color(255, 255, 255));
        selecSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        selecSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecSexoActionPerformed(evt);
            }
        });
        add(selecSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 124, 101, 30));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cuenta de Usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 66, -1, -1));

        entryPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryPesoActionPerformed(evt);
            }
        });
        add(entryPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 212, 56, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sexo ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 128, 40, 20));

        entryTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryTallaActionPerformed(evt);
            }
        });
        add(entryTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 246, 56, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de Nacimiento");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 171, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kg.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 218, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Peso");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 218, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("mtrs.");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 252, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Talla");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 252, -1, -1));

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        entryNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNombreActionPerformed(evt);
            }
        });
        add(entryNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 26, 205, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de Actividad Física");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        entryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryIdActionPerformed(evt);
            }
        });
        add(entryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 60, 155, -1));

        entryTiempoActFis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryTiempoActFisActionPerformed(evt);
            }
        });
        add(entryTiempoActFis, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 242, 35, -1));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        labelFoto.setText("\n");
        add(labelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 11, 94, 88));

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Contraseña");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        add(entryPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 94, 155, -1));

        botonImportarImag.setText("Importar Imagen");
        botonImportarImag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonImportarImag.setBorderPainted(false);
        botonImportarImag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImportarImagActionPerformed(evt);
            }
        });
        add(botonImportarImag, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 105, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoRegistroUsuario.png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void selecDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecDiaActionPerformed

    private void selecMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecMesActionPerformed

    private void selecSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecSexoActionPerformed

    private void entryPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryPesoActionPerformed

    private void entryTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryTallaActionPerformed

    private void entryNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNombreActionPerformed

    private void entryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryIdActionPerformed

    private void entryTiempoActFisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryTiempoActFisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryTiempoActFisActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        interfazLogin.setVisible(false);
        InterfazLogin.main(null);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        
        String nombre = entryNombre.getText();
        String id = entryId.getText();
        String pass = entryPass.getText();
        String sexo = (String)selecSexo.getSelectedItem();
        String dia =  (String)selecDia.getSelectedItem();
        String anio =  (String)selecAnio.getSelectedItem();
        String mes = String.valueOf(selecMes.getSelectedIndex() +1);
        String tipoActFis =(String)selecTipoActFis.getSelectedItem();
        String tiempoActFis = entryTiempoActFis.getText();
        String peso = entryPeso.getText();
        String talla = entryTalla.getText();
        
        if (ManejoDelUsuario.ValidarDatosRegistroUsuario(nombre,id,pass,tiempoActFis,talla,peso)){
            Object sx = Sexo.MASCULINO;
            Object tAct= TipoActividadFisica.INTENSA ;
            
            if(sexo.equals("Masculino"))
                sx = Sexo.MASCULINO;
            else if(sexo.equals("Femenino"))
                sx = Sexo.FEMENINO;
            if(tipoActFis.equals("Ligera"))
                tAct = TipoActividadFisica.LIGERA;
            else if(tipoActFis.equals("Moderada"))
                tAct = TipoActividadFisica.MODERADA;
            else if(tipoActFis.equals("Intensa"))
                tAct = TipoActividadFisica.INTENSA;
            
             usuario = new Usuario(nombre, id, pass, dia,  mes, anio, (Sexo) sx,  
                                              Double.parseDouble(peso), Double.parseDouble(talla),
                                              Integer.parseInt(tiempoActFis), (TipoActividadFisica) tAct);
             
            conexion.crearDBUsuario();
            conexion.insertarUsuario();/// inserta al usuario en la base de datos
            ManejoDeImagenes.guardarFotoPerfil();
            interfazLogin.setVisible(false);
            InterfazPrincipal1.main(null);
        }
        else{
            JOptionPane.showMessageDialog(this, "Faltan Campos Por Llenar.");
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonImportarImagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImportarImagActionPerformed
        ManejoDeImagenes.cargarFoto(labelFoto);
    }//GEN-LAST:event_botonImportarImagActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonImportarImag;
    public javax.swing.JButton botonRegistrar;
    public javax.swing.JTextField entryId;
    public javax.swing.JTextField entryNombre;
    private javax.swing.JPasswordField entryPass;
    public javax.swing.JTextField entryPeso;
    public javax.swing.JTextField entryTalla;
    public javax.swing.JTextField entryTiempoActFis;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel labelFoto;
    public javax.swing.JComboBox<String> selecAnio;
    public javax.swing.JComboBox<String> selecDia;
    public javax.swing.JComboBox<String> selecMes;
    public javax.swing.JComboBox<String> selecSexo;
    public javax.swing.JComboBox<String> selecTipoActFis;
    // End of variables declaration//GEN-END:variables
}